# Generated by Django 5.2 on 2026-02-11 13:17

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial de la empresa.', max_length=200, verbose_name='nombre')),
                ('razon_social', models.CharField(help_text='Razón social registrada.', max_length=200, verbose_name='razón social')),
                ('cuit', models.CharField(error_messages={'unique': 'Ya existe una empresa con este CUIT.'}, help_text='CUIT sin guiones (11 dígitos).', max_length=11, unique=True, validators=[clientes.models.validar_cuit], verbose_name='CUIT')),
                ('direccion', models.TextField(help_text='Dirección fiscal de la empresa.', verbose_name='dirección')),
                ('email', models.EmailField(help_text='Email de contacto de la empresa.', max_length=254, verbose_name='correo electrónico')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['cuit'], name='idx_empresa_cuit'), models.Index(fields=['estado'], name='idx_empresa_estado'), models.Index(fields=['nombre'], name='idx_empresa_nombre')],
            },
        ),
    ]
