# Generated by Django 5.2 on 2026-02-11 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este email.'}, help_text='Dirección de email utilizada para iniciar sesión.', max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado')], default='pendiente', help_text='Estado de verificación del usuario.', max_length=20, verbose_name='estado')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Colaborador', 'Colaborador'), ('Cliente', 'Cliente')], default='Cliente', help_text='Rol del usuario en el sistema.', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede iniciar sesión.', verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al admin.', verbose_name='es staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('empresas', models.ManyToManyField(blank=True, help_text='Empresas a las que está asociado el usuario.', related_name='usuarios', to='clientes.empresa', verbose_name='empresas asociadas')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='TokenActivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='token')),
                ('tipo', models.CharField(choices=[('activacion', 'Activación de cuenta'), ('recuperacion', 'Recuperación de contraseña')], default='activacion', max_length=20, verbose_name='tipo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('expira_en', models.DateTimeField(verbose_name='expira en')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_activacion', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'token de activación',
                'verbose_name_plural': 'tokens de activación',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='idx_usuario_email'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['estado'], name='idx_usuario_estado'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
    ]
