# Generated by Django 5.2 on 2026-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('saldo_cuenta_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cheque_pendiente_acreditar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('cheque_pendiente_debito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('saldo_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empresa', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2')], max_length=2)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['empresa'],
            },
        ),
        migrations.CreateModel(
            name='FCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('banco', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('cuotapartes', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'FCI',
                'verbose_name_plural': 'FCIs',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MonedaExtranjera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empresa', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2')], max_length=2)),
                ('saldo_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Moneda Extranjera',
                'verbose_name_plural': 'Monedas Extranjeras',
                'ordering': ['empresa'],
            },
        ),
        migrations.CreateModel(
            name='PlazoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('monto_invertido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('interes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_carga', models.DateField()),
            ],
            options={
                'verbose_name': 'Plazo Fijo',
                'verbose_name_plural': 'Plazos Fijos',
                'ordering': ['banco'],
            },
        ),
        migrations.CreateModel(
            name='TituloON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('cuotapartes_sem_ant', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('saldo_pesos_sem_ant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_usd_sem_ant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cuotapartes_actual', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('saldo_pesos_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_usd_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_cierre_pesos', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('valor_cierre_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Título / ON',
                'verbose_name_plural': 'Títulos / ONs',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorADepositar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField()),
                ('empresa', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2')], max_length=2)),
                ('mes_vencimiento', models.CharField(max_length=20)),
                ('anio_vencimiento', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Valor a Depositar',
                'verbose_name_plural': 'Valores a Depositar',
                'ordering': ['anio_vencimiento', 'mes_vencimiento'],
            },
        ),
    ]
