# Generated by Django 5.2 on 2026-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tituloon',
            name='tipo',
            field=models.CharField(choices=[('ON', 'Obligación Negociable'), ('Bono', 'Bono')], default='ON', max_length=10),
        ),
    ]
