# Generated by Django 5.2 on 2026-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_semana_anterior_caja_bancos_vad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tituloon',
            name='precio_manual',
            field=models.BooleanField(default=False, help_text='Marcar si el precio no se obtiene de IOL y debe cargarse manualmente.'),
        ),
    ]
