# Generated by Django 5.2 on 2026-02-25 18:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente de cuenta corriente.', max_length=255, unique=True, verbose_name='nombre')),
                ('vencido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Acumulación de deudas antiguas.', max_digits=15, verbose_name='vencido')),
                ('balance_especial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deuda de tipo especial, editable manualmente.', max_digits=15, verbose_name='balance/especial')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo. La baja solo se realiza desde el admin.', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Cliente Cuenta Corriente',
                'verbose_name_plural': 'Clientes Cuenta Corriente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden del periodo (1 al 5). 1 = más antiguo, 5 = más reciente.', verbose_name='orden')),
                ('periodo', models.DateField(help_text='Periodo activo. Siempre guardar el día 1 del mes.', unique=True, verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'Configuración de Mes',
                'verbose_name_plural': 'Configuración de Meses',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MesCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Mes del registro. Siempre guardar el día 1 del mes.', verbose_name='periodo')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='monto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meses', to='cuentas_corrientes.clientecc', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Mes Cuenta Corriente',
                'verbose_name_plural': 'Meses Cuenta Corriente',
                'ordering': ['periodo'],
                'unique_together': {('cliente', 'periodo')},
            },
        ),
    ]
