# Generated by Django 5.2 on 2026-03-04 19:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_corrientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmeses',
            name='sumatoria_facturacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sumatoria total de la columna al momento de crear el mes. Valor estático.', max_digits=15, verbose_name='sumatoria facturación'),
        ),
    ]
